# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Tencent.WeChat.Universal
PackageVersion: 4.1.2.17
InstallerType: nullsoft
Scope: machine
UpgradeBehavior: install
Protocols:
- xweixin
ProductCode: Weixin
Installers:
- Architecture: x64
  InstallerUrl: https://dldir1v6.qq.com/weixin/Universal/Windows/WeChatWin_4.1.2.exe
  InstallerSha256: 1186FA6F8510BDE2E5859FB87E82C08B28974CB1D5A6980B21B2A13A7FEFA8C6
ManifestType: installer
ManifestVersion: 1.10.0
